"""empty message

Revision ID: 2e404307f9f9
Revises: a59cf08dedf3
Create Date: 2017-07-12 23:02:06.710985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e404307f9f9'
down_revision = 'a59cf08dedf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_readings_timestamp'), 'readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_timestamp'), table_name='readings')
    # ### end Alembic commands ###
