"""empty message

Revision ID: 3d50897db729
Revises: 2e404307f9f9
Create Date: 2017-07-17 18:41:30.744854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d50897db729'
down_revision = '2e404307f9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_readings_ext_temp'), 'readings', ['ext_temp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_ext_temp'), table_name='readings')
    # ### end Alembic commands ###
